window.EIKEN5_QUESTIONS = [
  {
    id: "word-001",
    category: "word",
    type: "単語",
    question: "book の意味は？",
    reading: "ブック",
    speak: "book",
    choices: ["本", "机", "学校", "犬"],
    answer: "本",
    explanation: "book は「本」という意味です。"
  },
  {
    id: "word-002",
    category: "word",
    type: "単語",
    question: "morning の意味は？",
    reading: "モーニング",
    speak: "morning",
    choices: ["朝", "夜", "昼食", "日曜日"],
    answer: "朝",
    explanation: "Good morning. は「おはようございます」です。"
  },
  {
    id: "word-003",
    category: "word",
    type: "単語",
    question: "library の意味は？",
    reading: "ライブラリー",
    speak: "library",
    choices: ["図書館", "病院", "駅", "公園"],
    answer: "図書館",
    explanation: "library は本を読む場所、図書館です。"
  },
  {
    id: "word-004",
    category: "word",
    type: "単語",
    question: "sister の意味は？",
    reading: "シスター",
    speak: "sister",
    choices: ["姉・妹", "兄・弟", "父", "母"],
    answer: "姉・妹",
    explanation: "sister は姉または妹を表します。"
  },
  {
    id: "word-005",
    category: "word",
    type: "単語",
    question: "like の意味として正しいものは？",
    reading: "ライク",
    speak: "like",
    choices: ["好き", "走る", "眠る", "書く"],
    answer: "好き",
    explanation: "I like soccer. は「私はサッカーが好きです」です。"
  },
  {
    id: "word-006",
    category: "word",
    type: "単語",
    question: "school の意味は？",
    reading: "スクール",
    speak: "school",
    choices: ["学校", "家", "店", "駅"],
    answer: "学校",
    explanation: "school は「学校」です。"
  },
  {
    id: "word-007",
    category: "word",
    type: "単語",
    question: "teacher の意味は？",
    reading: "ティーチャー",
    speak: "teacher",
    choices: ["先生", "生徒", "友だち", "兄"],
    answer: "先生",
    explanation: "teacher は「先生」です。"
  },
  {
    id: "word-008",
    category: "word",
    type: "単語",
    question: "student の意味は？",
    reading: "スチューデント",
    speak: "student",
    choices: ["生徒", "先生", "医者", "歌手"],
    answer: "生徒",
    explanation: "student は「生徒、学生」です。"
  },
  {
    id: "word-009",
    category: "word",
    type: "単語",
    question: "friend の意味は？",
    reading: "フレンド",
    speak: "friend",
    choices: ["友だち", "家族", "先生", "父"],
    answer: "友だち",
    explanation: "friend は「友だち」です。"
  },
  {
    id: "word-010",
    category: "word",
    type: "単語",
    question: "family の意味は？",
    reading: "ファミリー",
    speak: "family",
    choices: ["家族", "学校", "朝食", "写真"],
    answer: "家族",
    explanation: "family は「家族」です。"
  },
  {
    id: "word-011",
    category: "word",
    type: "単語",
    question: "father の意味は？",
    reading: "ファーザー",
    speak: "father",
    choices: ["父", "母", "兄", "姉"],
    answer: "父",
    explanation: "father は「父」です。"
  },
  {
    id: "word-012",
    category: "word",
    type: "単語",
    question: "mother の意味は？",
    reading: "マザー",
    speak: "mother",
    choices: ["母", "父", "弟", "妹"],
    answer: "母",
    explanation: "mother は「母」です。"
  },
  {
    id: "word-013",
    category: "word",
    type: "単語",
    question: "brother の意味は？",
    reading: "ブラザー",
    speak: "brother",
    choices: ["兄・弟", "姉・妹", "母", "友だち"],
    answer: "兄・弟",
    explanation: "brother は兄または弟を表します。"
  },
  {
    id: "word-014",
    category: "word",
    type: "単語",
    question: "dog の意味は？",
    reading: "ドッグ",
    speak: "dog",
    choices: ["犬", "猫", "鳥", "魚"],
    answer: "犬",
    explanation: "dog は「犬」です。"
  },
  {
    id: "word-015",
    category: "word",
    type: "単語",
    question: "cat の意味は？",
    reading: "キャット",
    speak: "cat",
    choices: ["猫", "犬", "馬", "牛"],
    answer: "猫",
    explanation: "cat は「猫」です。"
  },
  {
    id: "word-016",
    category: "word",
    type: "単語",
    question: "apple の意味は？",
    reading: "アップル",
    speak: "apple",
    choices: ["りんご", "みかん", "牛乳", "水"],
    answer: "りんご",
    explanation: "apple は「りんご」です。"
  },
  {
    id: "word-017",
    category: "word",
    type: "単語",
    question: "water の意味は？",
    reading: "ウォーター",
    speak: "water",
    choices: ["水", "牛乳", "パン", "朝食"],
    answer: "水",
    explanation: "water は「水」です。"
  },
  {
    id: "word-018",
    category: "word",
    type: "単語",
    question: "music の意味は？",
    reading: "ミュージック",
    speak: "music",
    choices: ["音楽", "数学", "英語", "体育"],
    answer: "音楽",
    explanation: "music は「音楽」です。"
  },
  {
    id: "word-019",
    category: "word",
    type: "単語",
    question: "English の意味は？",
    reading: "イングリッシュ",
    speak: "English",
    choices: ["英語", "日本語", "音楽", "理科"],
    answer: "英語",
    explanation: "English は「英語」です。"
  },
  {
    id: "word-020",
    category: "word",
    type: "単語",
    question: "Japanese の意味は？",
    reading: "ジャパニーズ",
    speak: "Japanese",
    choices: ["日本語", "英語", "中国語", "数学"],
    answer: "日本語",
    explanation: "Japanese は「日本語、日本の」です。"
  },
  {
    id: "word-021",
    category: "word",
    type: "単語",
    question: "soccer の意味は？",
    reading: "サッカー",
    speak: "soccer",
    choices: ["サッカー", "野球", "テニス", "水泳"],
    answer: "サッカー",
    explanation: "soccer は「サッカー」です。"
  },
  {
    id: "word-022",
    category: "word",
    type: "単語",
    question: "baseball の意味は？",
    reading: "ベースボール",
    speak: "baseball",
    choices: ["野球", "サッカー", "バスケットボール", "テニス"],
    answer: "野球",
    explanation: "baseball は「野球」です。"
  },
  {
    id: "word-023",
    category: "word",
    type: "単語",
    question: "tennis の意味は？",
    reading: "テニス",
    speak: "tennis",
    choices: ["テニス", "野球", "水泳", "音楽"],
    answer: "テニス",
    explanation: "tennis は「テニス」です。"
  },
  {
    id: "word-024",
    category: "word",
    type: "単語",
    question: "swim の意味は？",
    reading: "スイム",
    speak: "swim",
    choices: ["泳ぐ", "走る", "読む", "書く"],
    answer: "泳ぐ",
    explanation: "swim は「泳ぐ」です。"
  },
  {
    id: "word-025",
    category: "word",
    type: "単語",
    question: "run の意味は？",
    reading: "ラン",
    speak: "run",
    choices: ["走る", "歌う", "食べる", "見る"],
    answer: "走る",
    explanation: "run は「走る」です。"
  },
  {
    id: "word-026",
    category: "word",
    type: "単語",
    question: "read の意味は？",
    reading: "リード",
    speak: "read",
    choices: ["読む", "書く", "聞く", "話す"],
    answer: "読む",
    explanation: "read は「読む」です。"
  },
  {
    id: "word-027",
    category: "word",
    type: "単語",
    question: "write の意味は？",
    reading: "ライト",
    speak: "write",
    choices: ["書く", "読む", "買う", "行く"],
    answer: "書く",
    explanation: "write は「書く」です。"
  },
  {
    id: "word-028",
    category: "word",
    type: "単語",
    question: "eat の意味は？",
    reading: "イート",
    speak: "eat",
    choices: ["食べる", "飲む", "見る", "来る"],
    answer: "食べる",
    explanation: "eat は「食べる」です。"
  },
  {
    id: "word-029",
    category: "word",
    type: "単語",
    question: "drink の意味は？",
    reading: "ドリンク",
    speak: "drink",
    choices: ["飲む", "食べる", "作る", "遊ぶ"],
    answer: "飲む",
    explanation: "drink は「飲む」です。"
  },
  {
    id: "word-030",
    category: "word",
    type: "単語",
    question: "go の意味は？",
    reading: "ゴー",
    speak: "go",
    choices: ["行く", "来る", "見る", "持つ"],
    answer: "行く",
    explanation: "go は「行く」です。"
  },
  {
    id: "word-031",
    category: "word",
    type: "単語",
    question: "come の意味は？",
    reading: "カム",
    speak: "come",
    choices: ["来る", "行く", "泳ぐ", "読む"],
    answer: "来る",
    explanation: "come は「来る」です。"
  },
  {
    id: "word-032",
    category: "word",
    type: "単語",
    question: "watch の意味は？",
    reading: "ウォッチ",
    speak: "watch",
    choices: ["見る", "書く", "走る", "飲む"],
    answer: "見る",
    explanation: "watch はテレビなどを「見る」という意味です。"
  },
  {
    id: "word-033",
    category: "word",
    type: "単語",
    question: "Sunday の意味は？",
    reading: "サンデー",
    speak: "Sunday",
    choices: ["日曜日", "月曜日", "土曜日", "金曜日"],
    answer: "日曜日",
    explanation: "Sunday は「日曜日」です。"
  },
  {
    id: "word-034",
    category: "word",
    type: "単語",
    question: "Monday の意味は？",
    reading: "マンデー",
    speak: "Monday",
    choices: ["月曜日", "日曜日", "火曜日", "木曜日"],
    answer: "月曜日",
    explanation: "Monday は「月曜日」です。"
  },
  {
    id: "word-035",
    category: "word",
    type: "単語",
    question: "today の意味は？",
    reading: "トゥデイ",
    speak: "today",
    choices: ["今日", "明日", "昨日", "朝"],
    answer: "今日",
    explanation: "today は「今日」です。"
  },
  {
    id: "word-036",
    category: "word",
    type: "単語",
    question: "tomorrow の意味は？",
    reading: "トゥモロー",
    speak: "tomorrow",
    choices: ["明日", "今日", "昨日", "週"],
    answer: "明日",
    explanation: "tomorrow は「明日」です。"
  },
  {
    id: "word-037",
    category: "word",
    type: "単語",
    question: "home の意味は？",
    reading: "ホーム",
    speak: "home",
    choices: ["家", "学校", "公園", "店"],
    answer: "家",
    explanation: "home は「家、自宅」です。"
  },
  {
    id: "word-038",
    category: "word",
    type: "単語",
    question: "park の意味は？",
    reading: "パーク",
    speak: "park",
    choices: ["公園", "図書館", "学校", "部屋"],
    answer: "公園",
    explanation: "park は「公園」です。"
  },
  {
    id: "word-039",
    category: "word",
    type: "単語",
    question: "station の意味は？",
    reading: "ステーション",
    speak: "station",
    choices: ["駅", "店", "家", "学校"],
    answer: "駅",
    explanation: "station は「駅」です。"
  },
  {
    id: "word-040",
    category: "word",
    type: "単語",
    question: "room の意味は？",
    reading: "ルーム",
    speak: "room",
    choices: ["部屋", "駅", "公園", "朝"],
    answer: "部屋",
    explanation: "room は「部屋」です。"
  },
  {
    id: "word-041",
    category: "word",
    type: "単語",
    question: "happy の意味は？",
    reading: "ハッピー",
    speak: "happy",
    choices: ["うれしい", "忙しい", "大きい", "新しい"],
    answer: "うれしい",
    explanation: "happy は「うれしい、幸せな」です。"
  },
  {
    id: "word-042",
    category: "word",
    type: "単語",
    question: "new の意味は？",
    reading: "ニュー",
    speak: "new",
    choices: ["新しい", "古い", "小さい", "速い"],
    answer: "新しい",
    explanation: "new は「新しい」です。"
  },
  {
    id: "word-043",
    category: "word",
    type: "単語",
    question: "big の意味は？",
    reading: "ビッグ",
    speak: "big",
    choices: ["大きい", "小さい", "長い", "短い"],
    answer: "大きい",
    explanation: "big は「大きい」です。"
  },
  {
    id: "word-044",
    category: "word",
    type: "単語",
    question: "small の意味は？",
    reading: "スモール",
    speak: "small",
    choices: ["小さい", "大きい", "新しい", "よい"],
    answer: "小さい",
    explanation: "small は「小さい」です。"
  },
  {
    id: "word-045",
    category: "word",
    type: "単語",
    question: "good の意味は？",
    reading: "グッド",
    speak: "good",
    choices: ["よい", "悪い", "新しい", "忙しい"],
    answer: "よい",
    explanation: "good は「よい」です。"
  },
  {
    id: "grammar-001",
    category: "grammar",
    type: "文法",
    question: "I (     ) a student.",
    reading: "アイ 空欄 ア スチューデント",
    speak: "I blank a student.",
    choices: ["am", "is", "are", "be"],
    answer: "am",
    explanation: "主語が I のときは am を使います。"
  },
  {
    id: "grammar-002",
    category: "grammar",
    type: "文法",
    question: "She (     ) tennis after school.",
    reading: "シー 空欄 テニス アフター スクール",
    speak: "She blank tennis after school.",
    choices: ["plays", "play", "playing", "to play"],
    answer: "plays",
    explanation: "主語が She なので、一般動詞に s がつきます。"
  },
  {
    id: "grammar-003",
    category: "grammar",
    type: "文法",
    question: "(     ) you like English?",
    reading: "空欄 ユー ライク イングリッシュ",
    speak: "Blank you like English?",
    choices: ["Do", "Is", "Are", "Does"],
    answer: "Do",
    explanation: "you を主語にした一般動詞の疑問文は Do you ...? です。"
  },
  {
    id: "grammar-004",
    category: "grammar",
    type: "文法",
    question: "This is (     ) apple.",
    reading: "ディス イズ 空欄 アップル",
    speak: "This is blank apple.",
    choices: ["an", "a", "the", "am"],
    answer: "an",
    explanation: "apple は母音の音で始まるので an を使います。"
  },
  {
    id: "grammar-005",
    category: "grammar",
    type: "文法",
    question: "Ken and Yui (     ) friends.",
    reading: "ケン アンド ユイ 空欄 フレンズ",
    speak: "Ken and Yui blank friends.",
    choices: ["are", "is", "am", "be"],
    answer: "are",
    explanation: "Ken and Yui は複数なので are を使います。"
  },
  {
    id: "conversation-001",
    category: "conversation",
    type: "会話",
    question: "A: How are you? B: (     )",
    reading: "ハウ アー ユー / 空欄",
    speak: "How are you? Blank.",
    choices: ["I'm fine, thank you.", "It's a pen.", "Yes, I do.", "At school."],
    answer: "I'm fine, thank you.",
    explanation: "How are you? には体調や気分を答えます。"
  },
  {
    id: "conversation-002",
    category: "conversation",
    type: "会話",
    question: "A: Nice to meet you. B: (     )",
    reading: "ナイス トゥー ミート ユー / 空欄",
    speak: "Nice to meet you. Blank.",
    choices: ["Nice to meet you, too.", "I am twelve.", "Here you are.", "Good night."],
    answer: "Nice to meet you, too.",
    explanation: "初対面のあいさつには Nice to meet you, too. と返します。"
  },
  {
    id: "conversation-003",
    category: "conversation",
    type: "会話",
    question: "A: What time is it? B: (     )",
    reading: "ワット タイム イズ イット / 空欄",
    speak: "What time is it? Blank.",
    choices: ["It's seven.", "I'm from Japan.", "I like music.", "Yes, it is."],
    answer: "It's seven.",
    explanation: "What time is it? は時刻をたずねる表現です。"
  },
  {
    id: "conversation-004",
    category: "conversation",
    type: "会話",
    question: "A: Thank you. B: (     )",
    reading: "サンキュー / 空欄",
    speak: "Thank you. Blank.",
    choices: ["You're welcome.", "I'm sorry.", "See you.", "Me, too."],
    answer: "You're welcome.",
    explanation: "Thank you. への返事は You're welcome. が自然です。"
  },
  {
    id: "conversation-005",
    category: "conversation",
    type: "会話",
    question: "A: Where are you from? B: (     )",
    reading: "ウェア アー ユー フロム / 空欄",
    speak: "Where are you from? Blank.",
    choices: ["I'm from Japan.", "I'm fine.", "It's Monday.", "I play soccer."],
    answer: "I'm from Japan.",
    explanation: "Where are you from? は出身地をたずねます。"
  },
  {
    id: "exam-001",
    category: "exam",
    type: "ミニ模試",
    question: "Tom has two (     ).",
    reading: "トム ハズ トゥー 空欄",
    speak: "Tom has two blank.",
    choices: ["dogs", "dog", "a dog", "doges"],
    answer: "dogs",
    explanation: "two のあとには複数形を使います。"
  },
  {
    id: "exam-002",
    category: "exam",
    type: "ミニ模試",
    question: "A: Is this your bag? B: (     )",
    reading: "イズ ディス ユア バッグ / 空欄",
    speak: "Is this your bag? Blank.",
    choices: ["Yes, it is.", "Yes, I do.", "No, I am.", "It is Sunday."],
    answer: "Yes, it is.",
    explanation: "Is this ...? には Yes, it is. / No, it isn't. で答えます。"
  },
  {
    id: "exam-003",
    category: "exam",
    type: "ミニ模試",
    question: "My brother (     ) soccer on Sundays.",
    reading: "マイ ブラザー 空欄 サッカー オン サンデイズ",
    speak: "My brother blank soccer on Sundays.",
    choices: ["plays", "play", "are", "am"],
    answer: "plays",
    explanation: "My brother は三人称単数なので plays です。"
  },
  {
    id: "exam-004",
    category: "exam",
    type: "ミニ模試",
    question: "Which word means 「昼食」?",
    reading: "ウィッチ ワード ミーンズ 昼食",
    speak: "Which word means the Japanese word shown?",
    choices: ["lunch", "breakfast", "dinner", "homework"],
    answer: "lunch",
    explanation: "lunch は「昼食」です。"
  },
  {
    id: "exam-005",
    category: "exam",
    type: "ミニ模試",
    question: "A: Can you swim? B: (     )",
    reading: "キャン ユー スイム / 空欄",
    speak: "Can you swim? Blank.",
    choices: ["Yes, I can.", "Yes, I am.", "No, it isn't.", "I am Ken."],
    answer: "Yes, I can.",
    explanation: "Can you ...? には can を使って答えます。"
  }
];
