window.EIKEN5_VOCABULARY = [
  { word: "I", reading: "アイ", meaning: "私は", group: "代名詞" },
  { word: "you", reading: "ユー", meaning: "あなたは、あなたたちは", group: "代名詞" },
  { word: "he", reading: "ヒー", meaning: "彼は", group: "代名詞" },
  { word: "she", reading: "シー", meaning: "彼女は", group: "代名詞" },
  { word: "it", reading: "イット", meaning: "それは", group: "代名詞" },
  { word: "we", reading: "ウィー", meaning: "私たちは", group: "代名詞" },
  { word: "they", reading: "ゼイ", meaning: "彼らは、それらは", group: "代名詞" },
  { word: "my", reading: "マイ", meaning: "私の", group: "代名詞" },
  { word: "your", reading: "ユア", meaning: "あなたの", group: "代名詞" },
  { word: "his", reading: "ヒズ", meaning: "彼の", group: "代名詞" },
  { word: "her", reading: "ハー", meaning: "彼女の", group: "代名詞" },
  { word: "this", reading: "ディス", meaning: "これ、この", group: "代名詞" },
  { word: "that", reading: "ザット", meaning: "あれ、あの", group: "代名詞" },

  { word: "father", reading: "ファーザー", meaning: "父", group: "家族・人" },
  { word: "mother", reading: "マザー", meaning: "母", group: "家族・人" },
  { word: "brother", reading: "ブラザー", meaning: "兄、弟", group: "家族・人" },
  { word: "sister", reading: "シスター", meaning: "姉、妹", group: "家族・人" },
  { word: "grandfather", reading: "グランドファーザー", meaning: "おじいさん、祖父", group: "家族・人" },
  { word: "grandmother", reading: "グランドマザー", meaning: "おばあさん、祖母", group: "家族・人" },
  { word: "family", reading: "ファミリー", meaning: "家族", group: "家族・人" },
  { word: "friend", reading: "フレンド", meaning: "友だち", group: "家族・人" },
  { word: "teacher", reading: "ティーチャー", meaning: "先生", group: "家族・人" },
  { word: "student", reading: "スチューデント", meaning: "生徒、学生", group: "家族・人" },
  { word: "boy", reading: "ボーイ", meaning: "男の子", group: "家族・人" },
  { word: "girl", reading: "ガール", meaning: "女の子", group: "家族・人" },
  { word: "man", reading: "マン", meaning: "男性", group: "家族・人" },
  { word: "woman", reading: "ウーマン", meaning: "女性", group: "家族・人" },
  { word: "child", reading: "チャイルド", meaning: "子ども", group: "家族・人" },
  { word: "name", reading: "ネーム", meaning: "名前", group: "家族・人" },

  { word: "school", reading: "スクール", meaning: "学校", group: "学校" },
  { word: "class", reading: "クラス", meaning: "授業、クラス", group: "学校" },
  { word: "classroom", reading: "クラスルーム", meaning: "教室", group: "学校" },
  { word: "book", reading: "ブック", meaning: "本", group: "学校" },
  { word: "notebook", reading: "ノートブック", meaning: "ノート", group: "学校" },
  { word: "pen", reading: "ペン", meaning: "ペン", group: "学校" },
  { word: "pencil", reading: "ペンシル", meaning: "えんぴつ", group: "学校" },
  { word: "bag", reading: "バッグ", meaning: "かばん", group: "学校" },
  { word: "desk", reading: "デスク", meaning: "机", group: "学校" },
  { word: "chair", reading: "チェア", meaning: "いす", group: "学校" },
  { word: "English", reading: "イングリッシュ", meaning: "英語", group: "学校" },
  { word: "Japanese", reading: "ジャパニーズ", meaning: "日本語、日本の", group: "学校" },
  { word: "math", reading: "マス", meaning: "数学", group: "学校" },
  { word: "music", reading: "ミュージック", meaning: "音楽", group: "学校" },
  { word: "homework", reading: "ホームワーク", meaning: "宿題", group: "学校" },

  { word: "home", reading: "ホーム", meaning: "家、自宅", group: "場所・もの" },
  { word: "house", reading: "ハウス", meaning: "家", group: "場所・もの" },
  { word: "room", reading: "ルーム", meaning: "部屋", group: "場所・もの" },
  { word: "kitchen", reading: "キッチン", meaning: "台所", group: "場所・もの" },
  { word: "door", reading: "ドア", meaning: "ドア", group: "場所・もの" },
  { word: "window", reading: "ウィンドウ", meaning: "窓", group: "場所・もの" },
  { word: "table", reading: "テーブル", meaning: "テーブル", group: "場所・もの" },
  { word: "bed", reading: "ベッド", meaning: "ベッド", group: "場所・もの" },
  { word: "box", reading: "ボックス", meaning: "箱", group: "場所・もの" },
  { word: "picture", reading: "ピクチャー", meaning: "絵、写真", group: "場所・もの" },
  { word: "computer", reading: "コンピューター", meaning: "コンピューター", group: "場所・もの" },
  { word: "phone", reading: "フォン", meaning: "電話", group: "場所・もの" },
  { word: "park", reading: "パーク", meaning: "公園", group: "場所・もの" },
  { word: "library", reading: "ライブラリー", meaning: "図書館", group: "場所・もの" },
  { word: "station", reading: "ステーション", meaning: "駅", group: "場所・もの" },
  { word: "store", reading: "ストア", meaning: "店", group: "場所・もの" },

  { word: "dog", reading: "ドッグ", meaning: "犬", group: "動物・食べ物" },
  { word: "cat", reading: "キャット", meaning: "猫", group: "動物・食べ物" },
  { word: "bird", reading: "バード", meaning: "鳥", group: "動物・食べ物" },
  { word: "fish", reading: "フィッシュ", meaning: "魚", group: "動物・食べ物" },
  { word: "apple", reading: "アップル", meaning: "りんご", group: "動物・食べ物" },
  { word: "orange", reading: "オレンジ", meaning: "オレンジ", group: "動物・食べ物" },
  { word: "banana", reading: "バナナ", meaning: "バナナ", group: "動物・食べ物" },
  { word: "bread", reading: "ブレッド", meaning: "パン", group: "動物・食べ物" },
  { word: "rice", reading: "ライス", meaning: "ごはん、米", group: "動物・食べ物" },
  { word: "egg", reading: "エッグ", meaning: "卵", group: "動物・食べ物" },
  { word: "milk", reading: "ミルク", meaning: "牛乳", group: "動物・食べ物" },
  { word: "water", reading: "ウォーター", meaning: "水", group: "動物・食べ物" },
  { word: "juice", reading: "ジュース", meaning: "ジュース", group: "動物・食べ物" },
  { word: "breakfast", reading: "ブレックファスト", meaning: "朝食", group: "動物・食べ物" },
  { word: "lunch", reading: "ランチ", meaning: "昼食", group: "動物・食べ物" },
  { word: "dinner", reading: "ディナー", meaning: "夕食", group: "動物・食べ物" },

  { word: "soccer", reading: "サッカー", meaning: "サッカー", group: "スポーツ・趣味" },
  { word: "baseball", reading: "ベースボール", meaning: "野球", group: "スポーツ・趣味" },
  { word: "tennis", reading: "テニス", meaning: "テニス", group: "スポーツ・趣味" },
  { word: "basketball", reading: "バスケットボール", meaning: "バスケットボール", group: "スポーツ・趣味" },
  { word: "swimming", reading: "スイミング", meaning: "水泳", group: "スポーツ・趣味" },
  { word: "sport", reading: "スポーツ", meaning: "スポーツ", group: "スポーツ・趣味" },
  { word: "game", reading: "ゲーム", meaning: "試合、ゲーム", group: "スポーツ・趣味" },
  { word: "movie", reading: "ムービー", meaning: "映画", group: "スポーツ・趣味" },
  { word: "song", reading: "ソング", meaning: "歌", group: "スポーツ・趣味" },
  { word: "piano", reading: "ピアノ", meaning: "ピアノ", group: "スポーツ・趣味" },
  { word: "guitar", reading: "ギター", meaning: "ギター", group: "スポーツ・趣味" },
  { word: "TV", reading: "ティービー", meaning: "テレビ", group: "スポーツ・趣味" },

  { word: "go", reading: "ゴー", meaning: "行く", group: "動詞" },
  { word: "come", reading: "カム", meaning: "来る", group: "動詞" },
  { word: "play", reading: "プレイ", meaning: "する、遊ぶ", group: "動詞" },
  { word: "like", reading: "ライク", meaning: "好き", group: "動詞" },
  { word: "have", reading: "ハブ", meaning: "持っている、食べる", group: "動詞" },
  { word: "want", reading: "ウォント", meaning: "ほしい、したい", group: "動詞" },
  { word: "eat", reading: "イート", meaning: "食べる", group: "動詞" },
  { word: "drink", reading: "ドリンク", meaning: "飲む", group: "動詞" },
  { word: "read", reading: "リード", meaning: "読む", group: "動詞" },
  { word: "write", reading: "ライト", meaning: "書く", group: "動詞" },
  { word: "watch", reading: "ウォッチ", meaning: "見る", group: "動詞" },
  { word: "see", reading: "シー", meaning: "見る、会う", group: "動詞" },
  { word: "listen", reading: "リッスン", meaning: "聞く", group: "動詞" },
  { word: "speak", reading: "スピーク", meaning: "話す", group: "動詞" },
  { word: "study", reading: "スタディ", meaning: "勉強する", group: "動詞" },
  { word: "run", reading: "ラン", meaning: "走る", group: "動詞" },
  { word: "swim", reading: "スイム", meaning: "泳ぐ", group: "動詞" },
  { word: "sing", reading: "シング", meaning: "歌う", group: "動詞" },
  { word: "make", reading: "メイク", meaning: "作る", group: "動詞" },
  { word: "help", reading: "ヘルプ", meaning: "助ける、手伝う", group: "動詞" },
  { word: "open", reading: "オープン", meaning: "開ける", group: "動詞" },
  { word: "close", reading: "クローズ", meaning: "閉める", group: "動詞" },

  { word: "good", reading: "グッド", meaning: "よい", group: "形容詞" },
  { word: "nice", reading: "ナイス", meaning: "すてきな、よい", group: "形容詞" },
  { word: "happy", reading: "ハッピー", meaning: "うれしい、幸せな", group: "形容詞" },
  { word: "big", reading: "ビッグ", meaning: "大きい", group: "形容詞" },
  { word: "small", reading: "スモール", meaning: "小さい", group: "形容詞" },
  { word: "new", reading: "ニュー", meaning: "新しい", group: "形容詞" },
  { word: "old", reading: "オールド", meaning: "古い、年をとった", group: "形容詞" },
  { word: "long", reading: "ロング", meaning: "長い", group: "形容詞" },
  { word: "short", reading: "ショート", meaning: "短い、背が低い", group: "形容詞" },
  { word: "hot", reading: "ホット", meaning: "暑い、熱い", group: "形容詞" },
  { word: "cold", reading: "コールド", meaning: "寒い、冷たい", group: "形容詞" },
  { word: "fast", reading: "ファスト", meaning: "速い", group: "形容詞" },
  { word: "busy", reading: "ビジー", meaning: "忙しい", group: "形容詞" },
  { word: "fine", reading: "ファイン", meaning: "元気な、晴れた", group: "形容詞" },

  { word: "Sunday", reading: "サンデー", meaning: "日曜日", group: "曜日・時間" },
  { word: "Monday", reading: "マンデー", meaning: "月曜日", group: "曜日・時間" },
  { word: "Tuesday", reading: "チューズデー", meaning: "火曜日", group: "曜日・時間" },
  { word: "Wednesday", reading: "ウェンズデー", meaning: "水曜日", group: "曜日・時間" },
  { word: "Thursday", reading: "サーズデー", meaning: "木曜日", group: "曜日・時間" },
  { word: "Friday", reading: "フライデー", meaning: "金曜日", group: "曜日・時間" },
  { word: "Saturday", reading: "サタデー", meaning: "土曜日", group: "曜日・時間" },
  { word: "today", reading: "トゥデイ", meaning: "今日", group: "曜日・時間" },
  { word: "tomorrow", reading: "トゥモロー", meaning: "明日", group: "曜日・時間" },
  { word: "morning", reading: "モーニング", meaning: "朝", group: "曜日・時間" },
  { word: "afternoon", reading: "アフタヌーン", meaning: "午後", group: "曜日・時間" },
  { word: "evening", reading: "イブニング", meaning: "夕方、晩", group: "曜日・時間" },
  { word: "night", reading: "ナイト", meaning: "夜", group: "曜日・時間" },
  { word: "time", reading: "タイム", meaning: "時、時間", group: "曜日・時間" },
  { word: "day", reading: "デイ", meaning: "日、1日", group: "曜日・時間" },
  { word: "week", reading: "ウィーク", meaning: "週", group: "曜日・時間" },
  { word: "month", reading: "マンス", meaning: "月、1か月", group: "曜日・時間" },
  { word: "year", reading: "イヤー", meaning: "年、1年", group: "曜日・時間" },
  { word: "birthday", reading: "バースデー", meaning: "誕生日", group: "曜日・時間" },
  { word: "holiday", reading: "ホリデー", meaning: "休日、祝日", group: "曜日・時間" },
  { word: "vacation", reading: "バケーション", meaning: "休暇", group: "曜日・時間" },
  { word: "now", reading: "ナウ", meaning: "今", group: "曜日・時間" },
  { word: "soon", reading: "スーン", meaning: "すぐに、まもなく", group: "曜日・時間" },
  { word: "early", reading: "アーリー", meaning: "早く、早い", group: "曜日・時間" },
  { word: "late", reading: "レイト", meaning: "遅く、遅い", group: "曜日・時間" },

  { word: "January", reading: "ジャニュアリー", meaning: "1月", group: "月・季節" },
  { word: "February", reading: "フェブラリー", meaning: "2月", group: "月・季節" },
  { word: "March", reading: "マーチ", meaning: "3月", group: "月・季節" },
  { word: "April", reading: "エイプリル", meaning: "4月", group: "月・季節" },
  { word: "May", reading: "メイ", meaning: "5月", group: "月・季節" },
  { word: "June", reading: "ジューン", meaning: "6月", group: "月・季節" },
  { word: "July", reading: "ジュライ", meaning: "7月", group: "月・季節" },
  { word: "August", reading: "オーガスト", meaning: "8月", group: "月・季節" },
  { word: "September", reading: "セプテンバー", meaning: "9月", group: "月・季節" },
  { word: "October", reading: "オクトーバー", meaning: "10月", group: "月・季節" },
  { word: "November", reading: "ノーベンバー", meaning: "11月", group: "月・季節" },
  { word: "December", reading: "ディセンバー", meaning: "12月", group: "月・季節" },
  { word: "spring", reading: "スプリング", meaning: "春", group: "月・季節" },
  { word: "summer", reading: "サマー", meaning: "夏", group: "月・季節" },
  { word: "fall", reading: "フォール", meaning: "秋", group: "月・季節" },
  { word: "autumn", reading: "オータム", meaning: "秋", group: "月・季節" },
  { word: "winter", reading: "ウィンター", meaning: "冬", group: "月・季節" },

  { word: "weather", reading: "ウェザー", meaning: "天気", group: "天気" },
  { word: "sunny", reading: "サニー", meaning: "晴れた", group: "天気" },
  { word: "cloudy", reading: "クラウディ", meaning: "くもった", group: "天気" },
  { word: "rainy", reading: "レイニー", meaning: "雨の", group: "天気" },
  { word: "snowy", reading: "スノーイー", meaning: "雪の", group: "天気" },
  { word: "windy", reading: "ウィンディ", meaning: "風の強い", group: "天気" },
  { word: "warm", reading: "ウォーム", meaning: "暖かい", group: "天気" },
  { word: "cool", reading: "クール", meaning: "涼しい", group: "天気" },
  { word: "rain", reading: "レイン", meaning: "雨、雨が降る", group: "天気" },
  { word: "snow", reading: "スノー", meaning: "雪、雪が降る", group: "天気" },
  { word: "wind", reading: "ウィンド", meaning: "風", group: "天気" },
  { word: "sun", reading: "サン", meaning: "太陽", group: "天気" },
  { word: "cloud", reading: "クラウド", meaning: "雲", group: "天気" },
  { word: "sky", reading: "スカイ", meaning: "空", group: "天気" },

  { word: "what", reading: "ワット", meaning: "何", group: "疑問詞・基本語" },
  { word: "who", reading: "フー", meaning: "だれ", group: "疑問詞・基本語" },
  { word: "where", reading: "ウェア", meaning: "どこ", group: "疑問詞・基本語" },
  { word: "when", reading: "ウェン", meaning: "いつ", group: "疑問詞・基本語" },
  { word: "how", reading: "ハウ", meaning: "どのように", group: "疑問詞・基本語" },
  { word: "yes", reading: "イエス", meaning: "はい", group: "疑問詞・基本語" },
  { word: "no", reading: "ノー", meaning: "いいえ", group: "疑問詞・基本語" },
  { word: "and", reading: "アンド", meaning: "そして、〜と", group: "疑問詞・基本語" },
  { word: "or", reading: "オア", meaning: "または", group: "疑問詞・基本語" },
  { word: "in", reading: "イン", meaning: "〜の中に、〜で", group: "疑問詞・基本語" },
  { word: "on", reading: "オン", meaning: "〜の上に、〜曜日に", group: "疑問詞・基本語" },
  { word: "under", reading: "アンダー", meaning: "〜の下に", group: "疑問詞・基本語" },
  { word: "from", reading: "フロム", meaning: "〜から、〜出身", group: "疑問詞・基本語" },
  { word: "to", reading: "トゥー", meaning: "〜へ、〜に", group: "疑問詞・基本語" },
  { word: "with", reading: "ウィズ", meaning: "〜といっしょに", group: "疑問詞・基本語" },
  { word: "please", reading: "プリーズ", meaning: "どうぞ、お願いします", group: "疑問詞・基本語" },
  { word: "thank", reading: "サンク", meaning: "感謝する", group: "疑問詞・基本語" },

  { word: "me", reading: "ミー", meaning: "私を、私に", group: "代名詞" },
  { word: "mine", reading: "マイン", meaning: "私のもの", group: "代名詞" },
  { word: "yours", reading: "ユアーズ", meaning: "あなたのもの", group: "代名詞" },
  { word: "him", reading: "ヒム", meaning: "彼を、彼に", group: "代名詞" },
  { word: "hers", reading: "ハーズ", meaning: "彼女のもの", group: "代名詞" },
  { word: "its", reading: "イッツ", meaning: "それの", group: "代名詞" },
  { word: "their", reading: "ゼア", meaning: "彼らの、それらの", group: "代名詞" },
  { word: "them", reading: "ゼム", meaning: "彼らを、それらを", group: "代名詞" },
  { word: "ours", reading: "アワーズ", meaning: "私たちのもの", group: "代名詞" },
  { word: "our", reading: "アワー", meaning: "私たちの", group: "代名詞" },
  { word: "us", reading: "アス", meaning: "私たちを、私たちに", group: "代名詞" },
  { word: "whose", reading: "フーズ", meaning: "だれの", group: "疑問詞・基本語" },
  { word: "which", reading: "ウィッチ", meaning: "どちらの、どれ", group: "疑問詞・基本語" },
  { word: "favorite", reading: "フェイバリット", meaning: "お気に入りの、大好きな", group: "疑問詞・基本語" },

  { word: "minute", reading: "ミニット", meaning: "分", group: "曜日・時間" },
  { word: "hour", reading: "アワー", meaning: "時間、1時間", group: "曜日・時間" },
  { word: "weekend", reading: "ウィークエンド", meaning: "週末", group: "曜日・時間" },
  { word: "midnight", reading: "ミッドナイト", meaning: "深夜", group: "曜日・時間" },
  { word: "one o'clock", reading: "ワン オクロック", meaning: "1時", group: "曜日・時間" },
  { word: "two o'clock", reading: "トゥー オクロック", meaning: "2時", group: "曜日・時間" },
  { word: "three o'clock", reading: "スリー オクロック", meaning: "3時", group: "曜日・時間" },
  { word: "four o'clock", reading: "フォー オクロック", meaning: "4時", group: "曜日・時間" },
  { word: "five o'clock", reading: "ファイブ オクロック", meaning: "5時", group: "曜日・時間" },
  { word: "six o'clock", reading: "シックス オクロック", meaning: "6時", group: "曜日・時間" },
  { word: "seven o'clock", reading: "セブン オクロック", meaning: "7時", group: "曜日・時間" },
  { word: "eight o'clock", reading: "エイト オクロック", meaning: "8時", group: "曜日・時間" },
  { word: "nine o'clock", reading: "ナイン オクロック", meaning: "9時", group: "曜日・時間" },
  { word: "ten o'clock", reading: "テン オクロック", meaning: "10時", group: "曜日・時間" },
  { word: "eleven o'clock", reading: "イレブン オクロック", meaning: "11時", group: "曜日・時間" },
  { word: "twelve o'clock", reading: "トゥエルブ オクロック", meaning: "12時", group: "曜日・時間" },

  { word: "Japan", reading: "ジャパン", meaning: "日本", group: "国・場所" },
  { word: "America", reading: "アメリカ", meaning: "アメリカ", group: "国・場所" },
  { word: "Canada", reading: "カナダ", meaning: "カナダ", group: "国・場所" },
  { word: "Australia", reading: "オーストラリア", meaning: "オーストラリア", group: "国・場所" },
  { word: "China", reading: "チャイナ", meaning: "中国", group: "国・場所" },
  { word: "France", reading: "フランス", meaning: "フランス", group: "国・場所" },
  { word: "Germany", reading: "ジャーマニー", meaning: "ドイツ", group: "国・場所" },
  { word: "country", reading: "カントリー", meaning: "国", group: "国・場所" },
  { word: "place", reading: "プレイス", meaning: "場所", group: "国・場所" },
  { word: "airport", reading: "エアポート", meaning: "空港", group: "国・場所" },
  { word: "hospital", reading: "ホスピタル", meaning: "病院", group: "国・場所" },
  { word: "post office", reading: "ポスト オフィス", meaning: "郵便局", group: "国・場所" },
  { word: "supermarket", reading: "スーパーマーケット", meaning: "スーパーマーケット", group: "国・場所" },
  { word: "mountain", reading: "マウンテン", meaning: "山", group: "国・場所" },
  { word: "sea", reading: "シー", meaning: "海", group: "国・場所" },
  { word: "restaurant", reading: "レストラン", meaning: "レストラン", group: "国・場所" },
  { word: "bedroom", reading: "ベッドルーム", meaning: "寝室", group: "場所・もの" },
  { word: "bathroom", reading: "バスルーム", meaning: "お風呂、トイレ", group: "場所・もの" },
  { word: "gym", reading: "ジム", meaning: "体育館、ジム", group: "場所・もの" },

  { word: "foggy", reading: "フォギー", meaning: "霧がかかった", group: "天気" },
  { word: "sunshine", reading: "サンシャイン", meaning: "日光、晴天", group: "天気" },
  { word: "shower", reading: "シャワー", meaning: "にわか雨", group: "天気" },
  { word: "fog", reading: "フォグ", meaning: "霧", group: "天気" },
  { word: "clear up", reading: "クリア アップ", meaning: "晴れる", group: "天気" },

  { word: "children", reading: "チルドレン", meaning: "子どもたち", group: "家族・人" },
  { word: "parent", reading: "ペアレント", meaning: "親", group: "家族・人" },
  { word: "cousin", reading: "カズン", meaning: "いとこ", group: "家族・人" },
  { word: "person", reading: "パーソン", meaning: "人", group: "家族・人" },
  { word: "people", reading: "ピープル", meaning: "人々", group: "家族・人" },
  { word: "doctor", reading: "ドクター", meaning: "医者", group: "職業" },
  { word: "driver", reading: "ドライバー", meaning: "運転手", group: "職業" },
  { word: "pilot", reading: "パイロット", meaning: "パイロット", group: "職業" },
  { word: "singer", reading: "シンガー", meaning: "歌手", group: "職業" },
  { word: "waiter", reading: "ウェイター", meaning: "ウェイター", group: "職業" },
  { word: "worker", reading: "ワーカー", meaning: "働く人", group: "職業" },
  { word: "player", reading: "プレイヤー", meaning: "選手、演奏者", group: "職業" },
  { word: "dancer", reading: "ダンサー", meaning: "ダンサー", group: "職業" },
  { word: "pianist", reading: "ピアニスト", meaning: "ピアニスト", group: "職業" },
  { word: "job", reading: "ジョブ", meaning: "仕事", group: "職業" },

  { word: "badminton", reading: "バドミントン", meaning: "バドミントン", group: "スポーツ・趣味" },
  { word: "table tennis", reading: "テーブル テニス", meaning: "卓球", group: "スポーツ・趣味" },
  { word: "surfing", reading: "サーフィン", meaning: "サーフィン", group: "スポーツ・趣味" },
  { word: "marathon", reading: "マラソン", meaning: "マラソン", group: "スポーツ・趣味" },
  { word: "boxing", reading: "ボクシング", meaning: "ボクシング", group: "スポーツ・趣味" },

  { word: "color", reading: "カラー", meaning: "色", group: "日常名詞" },
  { word: "flower", reading: "フラワー", meaning: "花", group: "日常名詞" },
  { word: "test", reading: "テスト", meaning: "テスト", group: "日常名詞" },
  { word: "fruit", reading: "フルーツ", meaning: "果物", group: "日常名詞" },
  { word: "dictionary", reading: "ディクショナリー", meaning: "辞書", group: "日常名詞" },
  { word: "passport", reading: "パスポート", meaning: "パスポート", group: "日常名詞" },
  { word: "food", reading: "フード", meaning: "食べ物", group: "日常名詞" },
  { word: "animal", reading: "アニマル", meaning: "動物", group: "日常名詞" },
  { word: "blackboard", reading: "ブラックボード", meaning: "黒板", group: "日常名詞" },
  { word: "tea", reading: "ティー", meaning: "お茶", group: "日常名詞" },
  { word: "calendar", reading: "カレンダー", meaning: "カレンダー", group: "日常名詞" },
  { word: "shoes", reading: "シューズ", meaning: "くつ", group: "日常名詞" },
  { word: "umbrella", reading: "アンブレラ", meaning: "かさ", group: "日常名詞" },
  { word: "newspaper", reading: "ニュースペーパー", meaning: "新聞", group: "日常名詞" },
  { word: "hair", reading: "ヘア", meaning: "髪", group: "日常名詞" },
  { word: "diary", reading: "ダイアリー", meaning: "日記", group: "日常名詞" },
  { word: "letter", reading: "レター", meaning: "手紙、文字", group: "日常名詞" },
  { word: "wall", reading: "ウォール", meaning: "壁", group: "日常名詞" },
  { word: "doll", reading: "ドール", meaning: "人形", group: "日常名詞" },
  { word: "grape", reading: "グレープ", meaning: "ぶどう", group: "日常名詞" },
  { word: "camera", reading: "カメラ", meaning: "カメラ", group: "日常名詞" },
  { word: "mouth", reading: "マウス", meaning: "口", group: "日常名詞" },
  { word: "coin", reading: "コイン", meaning: "硬貨", group: "日常名詞" },
  { word: "garden", reading: "ガーデン", meaning: "庭", group: "日常名詞" },
  { word: "idea", reading: "アイデア", meaning: "考え、意見", group: "日常名詞" },
  { word: "club", reading: "クラブ", meaning: "クラブ、部", group: "日常名詞" },
  { word: "art", reading: "アート", meaning: "芸術、美術", group: "日常名詞" },
  { word: "number", reading: "ナンバー", meaning: "数、番号", group: "日常名詞" },
  { word: "history", reading: "ヒストリー", meaning: "歴史", group: "日常名詞" },
  { word: "story", reading: "ストーリー", meaning: "物語、話", group: "日常名詞" },
  { word: "subject", reading: "サブジェクト", meaning: "科目、主題", group: "日常名詞" },
  { word: "plane", reading: "プレイン", meaning: "飛行機", group: "日常名詞" },
  { word: "dish", reading: "ディッシュ", meaning: "皿、料理", group: "日常名詞" },
  { word: "tree", reading: "ツリー", meaning: "木", group: "日常名詞" },

  { word: "get", reading: "ゲット", meaning: "得る、手に入れる", group: "動詞" },
  { word: "take", reading: "テイク", meaning: "取る、連れて行く", group: "動詞" },
  { word: "work", reading: "ワーク", meaning: "働く", group: "動詞" },
  { word: "use", reading: "ユーズ", meaning: "使う", group: "動詞" },
  { word: "wash", reading: "ウォッシュ", meaning: "洗う", group: "動詞" },
  { word: "cook", reading: "クック", meaning: "料理する", group: "動詞" },
  { word: "sleep", reading: "スリープ", meaning: "寝る", group: "動詞" },
  { word: "buy", reading: "バイ", meaning: "買う", group: "動詞" },
  { word: "look", reading: "ルック", meaning: "見る", group: "動詞" },
  { word: "know", reading: "ノウ", meaning: "知っている", group: "動詞" },
  { word: "sit", reading: "シット", meaning: "座る", group: "動詞" },
  { word: "clean", reading: "クリーン", meaning: "掃除する、きれいな", group: "動詞" },
  { word: "meet", reading: "ミート", meaning: "会う", group: "動詞" },
  { word: "walk", reading: "ウォーク", meaning: "歩く", group: "動詞" },
  { word: "start", reading: "スタート", meaning: "始める", group: "動詞" },
  { word: "talk", reading: "トーク", meaning: "話す", group: "動詞" },
  { word: "teach", reading: "ティーチ", meaning: "教える", group: "動詞" },
  { word: "do", reading: "ドゥー", meaning: "する、行う", group: "動詞" },
  { word: "think", reading: "シンク", meaning: "考える、思う", group: "動詞" },
  { word: "need", reading: "ニード", meaning: "必要とする", group: "動詞" },
  { word: "give", reading: "ギブ", meaning: "あげる、与える", group: "動詞" },
  { word: "stop", reading: "ストップ", meaning: "止まる、止める", group: "動詞" },
  { word: "dance", reading: "ダンス", meaning: "ダンスする", group: "動詞" },
  { word: "love", reading: "ラブ", meaning: "愛する、大好き", group: "動詞" },
  { word: "live", reading: "リブ", meaning: "住む、生きる", group: "動詞" },
  { word: "stand", reading: "スタンド", meaning: "立つ", group: "動詞" },
  { word: "wait", reading: "ウェイト", meaning: "待つ", group: "動詞" },
  { word: "put", reading: "プット", meaning: "置く、入れる", group: "動詞" },
  { word: "ride", reading: "ライド", meaning: "乗る", group: "動詞" },
  { word: "learn", reading: "ラーン", meaning: "学ぶ、習う", group: "動詞" },
  { word: "enjoy", reading: "エンジョイ", meaning: "楽しむ", group: "動詞" },
  { word: "practice", reading: "プラクティス", meaning: "練習する", group: "動詞" },
  { word: "ask", reading: "アスク", meaning: "たずねる、お願いする", group: "動詞" },
  { word: "tell", reading: "テル", meaning: "言う、教える", group: "動詞" },
  { word: "fly", reading: "フライ", meaning: "飛ぶ", group: "動詞" },
  { word: "jump", reading: "ジャンプ", meaning: "ジャンプする", group: "動詞" },
  { word: "stay", reading: "ステイ", meaning: "とどまる、泊まる", group: "動詞" },
  { word: "move", reading: "ムーブ", meaning: "動く、動かす", group: "動詞" },
  { word: "turn", reading: "ターン", meaning: "曲がる、回る", group: "動詞" },
  { word: "visit", reading: "ビジット", meaning: "訪ねる", group: "動詞" },
  { word: "try", reading: "トライ", meaning: "試す、やってみる", group: "動詞" }
];
